#!/bin/bash
if [ "$(whoami)" != "root" ]; then
	echo "This script must be run as root"
	echo "Try with 'sudo ./enableIpForwarding'"
else
	echo -e "Temporary or permanent?\n0- Temporary\n1- Permanent"
	printf ">>> "
	read mode
	if [ "$mode" == "0" ]; then
		echo 1 > /proc/sys/net/ipv4/ip_forward
		echo "Done!"
	elif [ "$mode" == "1" ]; then
		sysctl -w net.ipv4.ip_forward=1
		echo "Done!"
	else
		echo "Please select a valid option"
	fi
fi
