#!/bin/bash
if [ "$(whoami)" != "root" ]; then
	echo "This script must be run as root"
	echo "Try with 'sudo ./enableIpForwarding'"
else
	echo -e "Select mode:\n0: disabled\n1: enabled\n2: adaptive"
	printf ">>> "
	read mode
	for i in /proc/sys/net/ipv4/conf/*/rp_filter; do
		echo $mode > $i
	done
fi
